spring:
  application:
    name: test-case-helper
    url: ${APPLICATION_PROD_URL}
  datasource:
    url: ${SPRING_DATASOURCE_PROD_URL}
    username: ${SPRING_DATASOURCE_PROD_USERNAME}
    password: ${SPRING_DATASOURCE_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${SPRING_PROD_REDIS_HOST}
      port: 6379
  cache:
    type: redis
logging:
  level:
    root: warn
    org.springframework: warn
    org.hibernate.SQL: error
    org.hibernate.type: error
    com.your.package: info
  file:
    name: /var/log/testCaseHelper/application.log
server:
  port: 4040

jwt:
  secret: ${JWT_PROD_SECRET}

admin:
  token: ${ADMIN_PROD_TOKEN}

cors:
  origin: ${ALLOWED_PROD_ORIGIN}
