spring:
  application:
    name: test-case-helper
    url: ${APPLICATION_DEV_URL}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: 6379
  cache:
    type: redis
logging:
  level:
    root: info
    org.springframework: info
    org.hibernate.sql: info
    org.hibernate.type: trace
    com.your.package: debug
  file:
    name: logs/dev-application.log
server:
  port: 4040

jwt:
  secret: ${JWT_SECRET}

admin:
  token: ${ADMIN_TOKEN}

cors:
  origin: ${ALLOWED_ORIGIN}
